/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    media: Media;
    experience: Experience;
    'project-filters': ProjectFilter;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    'project-filters': ProjectFiltersSelect<false> | ProjectFiltersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    skills: Skill;
    teo: Teo;
    'projects-page': ProjectsPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    skills: SkillsSelect<false> | SkillsSelect<true>;
    teo: TeoSelect<false> | TeoSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL amigable (ej: analitica-predictiva-vivienda)
   */
  slug: string;
  description: string;
  /**
   * Etiqueta chica sobre el título (ej: Data Engineering).
   */
  category?: string | null;
  /**
   * Filtros a los que pertenece este proyecto (puede tener varios).
   */
  filters?: (number | ProjectFilter)[] | null;
  /**
   * Se muestra como tarjeta grande en el Home. Marcá uno solo.
   */
  featured?: boolean | null;
  /**
   * Datos clave a la derecha de la fila (se muestran hasta 3).
   */
  metrics?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  repositoryUrl?: string | null;
  liveUrl?: string | null;
  image: number | Media;
  /**
   * Escribí con "/" para insertar títulos, listas, notas, imágenes, videos, código y botones. Seleccioná texto para darle formato, link, color o resaltado.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-filters".
 */
export interface ProjectFilter {
  id: number;
  /**
   * Texto del botón (ej: AI, Real-Time NLP, Credit ML).
   */
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  company: string;
  role: string;
  startDate: string;
  /**
   * Dejar vacío si es el trabajo actual
   */
  endDate?: string | null;
  /**
   * Opcional: un párrafo corto de introducción. Los puntos van en "Highlights".
   */
  description?: string | null;
  /**
   * Una fila por punto. Se muestran como viñetas y se reordenan arrastrando.
   */
  highlights?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Nombre para encontrarlo en el admin (ej: CV octubre 2026).
   */
  title: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'project-filters';
        value: number | ProjectFilter;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  filters?: T;
  featured?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  repositoryUrl?: T;
  liveUrl?: T;
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  company?: T;
  role?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-filters_select".
 */
export interface ProjectFiltersSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * Cada fila es una columna del Home. Se reordenan arrastrando.
   */
  groups?:
    | {
        /**
         * Nombre de la columna (ej: Data Engineering).
         */
        title: string;
        icon?: ('database' | 'chart' | 'sparkles' | 'workflow' | 'shield' | 'zap' | 'layers' | 'users') | null;
        /**
         * Proyectos de esta columna (casos de estudio). Las herramientas se calculan solas con el Tech Stack de cada proyecto.
         */
        projects?: (number | Project)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teo".
 */
export interface Teo {
  id: number;
  /**
   * Etiqueta chica sobre el título (ej: Off the clock).
   */
  kicker?: string | null;
  title?: string | null;
  lead?: string | null;
  /**
   * Foto grande de la portada.
   */
  heroPhoto?: (number | null) | Media;
  galleryTitle?: string | null;
  /**
   * Galería: elegí varias fotos a la vez y ordenalas arrastrando.
   */
  photos?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  /**
   * Bloques de la página, en el orden en que se muestran: arrastrá las filas para reordenarlas. Cada sección muestra los proyectos que tengan alguno de sus filtros. Un proyecto aparece una sola vez (en la primera sección que lo incluya). Los que no estén en ninguna van al final, en "More work".
   */
  sections?:
    | {
        title: string;
        description?: string | null;
        /**
         * Filtros de esta sección: muestra los proyectos que tengan cualquiera de ellos. Sin filtros, la sección queda vacía y no se muestra.
         */
        filters?: (number | ProjectFilter)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Tu foto (Home y About). Cuadrada o casi cuadrada se ve mejor.
   */
  profilePhoto?: (number | null) | Media;
  /**
   * PDF del currículum. Podés elegir uno por idioma (cambiá el Locale arriba); si falta el del español se usa el de inglés.
   */
  resume?: (number | null) | Document;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        icon?: T;
        projects?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teo_select".
 */
export interface TeoSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  heroPhoto?: T;
  galleryTitle?: T;
  photos?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        filters?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  profilePhoto?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjLedeBlock".
 */
export interface PrjLedeBlock {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjLede';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjCalloutBlock".
 */
export interface PrjCalloutBlock {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjCallout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjMetricsBlock".
 */
export interface PrjMetricsBlock {
  items?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjMetrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjImageBlock".
 */
export interface PrjImageBlock {
  image: number | Media;
  caption?: string | null;
  frame?: ('none' | 'browser') | null;
  /**
   * Opcional: si lo completás, la imagen lleva a esta dirección (https://... o /projects/...).
   */
  linkUrl?: string | null;
  newTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjVideoBlock".
 */
export interface PrjVideoBlock {
  /**
   * Link de YouTube o Vimeo, o de un archivo de video (.mp4).
   */
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjCodeBlock".
 */
export interface PrjCodeBlock {
  /**
   * Opcional: nombre del archivo o "Terminal".
   */
  title?: string | null;
  language?:
    | (
        | 'bash'
        | 'powershell'
        | 'javascript'
        | 'typescript'
        | 'jsx'
        | 'tsx'
        | 'python'
        | 'r'
        | 'sql'
        | 'json'
        | 'yaml'
        | 'html'
        | 'css'
        | 'markdown'
        | 'dockerfile'
        | 'diff'
        | 'java'
        | 'csharp'
        | 'cpp'
        | 'go'
        | 'rust'
        | 'php'
        | 'text'
      )
    | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjCode';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrjButtonsBlock".
 */
export interface PrjButtonsBlock {
  items?:
    | {
        label: string;
        /**
         * Dirección completa (https://...) o interna (/projects).
         */
        url: string;
        style?: ('primary' | 'ghost') | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prjButtons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}